/**
MIT License

Copyright (c) 2025 arfy slowy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
**/

#ifndef XVR_TOKEN_TYPES_H
#define XVR_TOKEN_TYPES_H

typedef enum Xvr_TokenType {
  // token null
  XVR_TOKEN_NULL,

  // variable name
  XVR_TOKEN_IDENTIFIER,

  // types
  XVR_TOKEN_TYPE_TYPE,
  XVR_TOKEN_TYPE_BOOLEAN,
  XVR_TOKEN_TYPE_INTEGER,
  XVR_TOKEN_TYPE_FLOAT,
  XVR_TOKEN_TYPE_STRING,
  XVR_TOKEN_TYPE_ARRAY,
  XVR_TOKEN_TYPE_DICTIONARY,
  XVR_TOKEN_TYPE_FUNCTION,
  XVR_TOKEN_TYPE_OPAQUE,
  XVR_TOKEN_TYPE_ANY,

  // keywords and reserved words
  XVR_TOKEN_KEYWORD_AS,
  XVR_TOKEN_KEYWORD_ASSERT,
  XVR_TOKEN_KEYWORD_BREAK,
  XVR_TOKEN_KEYWORD_CLASS,
  XVR_TOKEN_KEYWORD_CONST,
  XVR_TOKEN_KEYWORD_CONTINUE,
  XVR_TOKEN_KEYWORD_DO,
  XVR_TOKEN_KEYWORD_ELSE,
  XVR_TOKEN_KEYWORD_EXPORT,
  XVR_TOKEN_KEYWORD_FOR,
  XVR_TOKEN_KEYWORD_FOREACH,
  XVR_TOKEN_KEYWORD_FUNCTION,
  XVR_TOKEN_KEYWORD_IF,
  XVR_TOKEN_KEYWORD_IMPORT,
  XVR_TOKEN_KEYWORD_IN,
  XVR_TOKEN_KEYWORD_OF,
  XVR_TOKEN_KEYWORD_PRINT,
  XVR_TOKEN_KEYWORD_RETURN,
  XVR_TOKEN_KEYWORD_TYPEAS,
  XVR_TOKEN_KEYWORD_TYPEOF,
  XVR_TOKEN_KEYWORD_VAR,
  XVR_TOKEN_KEYWORD_WHILE,
  XVR_TOKEN_KEYWORD_YIELD,

  // literal values
  XVR_TOKEN_LITERAL_TRUE,
  XVR_TOKEN_LITERAL_FALSE,
  XVR_TOKEN_LITERAL_INTEGER,
  XVR_TOKEN_LITERAL_FLOAT,
  XVR_TOKEN_LITERAL_STRING,

  // math operators
  XVR_TOKEN_OPERATOR_ADD,
  XVR_TOKEN_OPERATOR_SUBTRACT,
  XVR_TOKEN_OPERATOR_MULTIPLY,
  XVR_TOKEN_OPERATOR_DIVIDE,
  XVR_TOKEN_OPERATOR_MODULO,
  XVR_TOKEN_OPERATOR_ADD_ASSIGN,
  XVR_TOKEN_OPERATOR_SUBTRACT_ASSIGN,
  XVR_TOKEN_OPERATOR_MULTIPLY_ASSIGN,
  XVR_TOKEN_OPERATOR_DIVIDE_ASSIGN,
  XVR_TOKEN_OPERATOR_MODULO_ASSIGN,
  XVR_TOKEN_OPERATOR_INCREMENT,
  XVR_TOKEN_OPERATOR_DECREMENT,
  XVR_TOKEN_OPERATOR_ASSIGN,

  // comparator operators
  XVR_TOKEN_OPERATOR_COMPARE_EQUAL,
  XVR_TOKEN_OPERATOR_COMPARE_NOT,
  XVR_TOKEN_OPERATOR_COMPARE_LESS,
  XVR_TOKEN_OPERATOR_COMPARE_LESS_EQUAL,
  XVR_TOKEN_OPERATOR_COMPARE_GREATER,
  XVR_TOKEN_OPERATOR_COMPARE_GREATER_EQUAL,

  // structural operators
  XVR_TOKEN_OPERATOR_PAREN_LEFT,
  XVR_TOKEN_OPERATOR_PAREN_RIGHT,
  XVR_TOKEN_OPERATOR_BRACKET_LEFT,
  XVR_TOKEN_OPERATOR_BRACKET_RIGHT,
  XVR_TOKEN_OPERATOR_BRACE_LEFT,
  XVR_TOKEN_OPERATOR_BRACE_RIGHT,

  // other operators
  XVR_TOKEN_OPERATOR_AND,
  XVR_TOKEN_OPERATOR_OR,
  XVR_TOKEN_OPERATOR_NEGATE,
  XVR_TOKEN_OPERATOR_QUESTION,
  XVR_TOKEN_OPERATOR_COLON,

  XVR_TOKEN_OPERATOR_SEMICOLON,
  XVR_TOKEN_OPERATOR_COMMA,

  XVR_TOKEN_OPERATOR_DOT,    // .
  XVR_TOKEN_OPERATOR_CONCAT, // ..
  XVR_TOKEN_OPERATOR_REST,   // ...

  // unused operators
  XVR_TOKEN_OPERATOR_AMPERSAND, // &
  XVR_TOKEN_OPERATOR_PIPE,      // |

  // meta tokens
  XVR_TOKEN_PASS,
  XVR_TOKEN_ERROR,
  XVR_TOKEN_EOF,

} Xvr_TokenType;
#endif // !XVR_TOKEN_TYPES_H
